FROM ubuntu

# Update package list and install prerequisites
RUN apt-get update && \
    apt-get install -y build-essential python3-pip net-tools iputils-ping iproute2 curl

# Install Node.js 
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# Expose required ports
#For Nextjs 
EXPOSE 3000
#For http/webSocket nodejs server
EXPOSE 8000

#udp ports for mediasoup produce and consume transports
EXPOSE 2000-2999
EXPOSE 10000-59999
